<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>da72d312-cc35-45d6-afa3-fd48a2711dcb</UserSecretsId>
  </PropertyGroup>

  <Target Name="BuildTailwindCss" BeforeTargets="Build" Condition="Exists('$(ProjectDir)node_modules')">
    <Exec Command="npm run build:css" WorkingDirectory="$(ProjectDir)" />
  </Target>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
  </ItemGroup>

</Project>
